{
    "HttpCalls": [
        {
            "RequestUriPath": "/sdk-sample-nh/messages?api-version=2017-04",
            "StatusCode": 201,
            "Headers": {
                "Date": "Wed, 07 Nov 2018 00:18:20 GMT",
                "Transfer-Encoding": "chunked",
                "Location": "https://sdk-sample-namespace.servicebus.windows.net/sdk-sample-nh/messages/0de2de92084545cfa6f5159cc54663b0-20181107001821-33331921-11?api-version=2017-04",
                "Server": "Microsoft-HTTPAPI/2.0"
            },
            "ContentHeaders": {
                "Content-Type": "application/xml; charset=utf-8"
            },
            "Content": null
        }
    ],
    "Guids": []
}
