{
    "HttpCalls": [
        {
            "RequestUriPath": "/sdk-sample-nh/messages?api-version=2017-04",
            "StatusCode": 201,
            "Headers": {
                "Date": "Wed, 07 Nov 2018 00:18:33 GMT",
                "Transfer-Encoding": "chunked",
                "Location": "https://sdk-sample-namespace.servicebus.windows.net/sdk-sample-nh/messages/73622a22797441e4b434e8c2c14112ce-20181107001834-33331921-18?api-version=2017-04",
                "Server": "Microsoft-HTTPAPI/2.0"
            },
            "ContentHeaders": {
                "Content-Type": "application/xml; charset=utf-8"
            },
            "Content": null
        }
    ],
    "Guids": []
}
