{
   "HttpCalls":[
      {
         "RequestUriPath":"/sdk-sample-nh/messages?api-version=2020-06",
         "StatusCode":201,
         "Headers":{
            "Strict-Transport-Security":"max-age=2592000",
            "Date":"Thu, 23 Jul 2020 04:27:57 GMT",
            "Location":"https://sdk-sample-namespace.notificationhub.int7.windows-int.net/sdk-sample-nh/messages/08fd2acb81ef40179d2cffb2f0bb61fb-20200723042757-586152-5?api-version=2020-06",
            "Server":"Microsoft-HTTPAPI/2.0"
         },
         "ContentHeaders":{
            "Content-Length":"0",
            "Content-Type":"application/xml; charset=utf-8"
         },
         "Content":null
      }
   ],
   "Guids":[

   ]
}