{"HttpCalls":[{"RequestUriPath":"/sdk-sample-nh/messages?api-version=2017-04","StatusCode":201,"Headers":{"Date":"Wed, 07 Nov 2018 00:18:33 GMT","Transfer-Encoding":"chunked","Location":"https://sdk-sample-namespace.servicebus.windows.net/sdk-sample-nh/messages/cec4b172178f48e9a801f7d2ebbaa471-20181107001833-33331921-12?api-version=2017-04","Server":"Microsoft-HTTPAPI/2.0"},"ContentHeaders":{"Content-Type":"application/xml; charset=utf-8"},"Content":null}],"Guids":[]}