{
    "HttpCalls": [
        {
            "RequestUriPath": "/sdk-sample-nh/messages?api-version=2017-04",
            "StatusCode": 201,
            "Headers": {
                "Date": "Wed, 07 Nov 2018 00:18:27 GMT",
                "Transfer-Encoding": "chunked",
                "Location": "https://sdk-sample-namespace.servicebus.windows.net/sdk-sample-nh/messages/4651c1ec2b614f14bfec41c62ca000b1-20181107001828-33331921-15?api-version=2017-04",
                "Server": "Microsoft-HTTPAPI/2.0"
            },
            "ContentHeaders": {
                "Content-Type": "application/xml; charset=utf-8"
            },
            "Content": null
        }
    ],
    "Guids": []
}
